export enum ValidationAlertCode {
  LIMITE_ANTIGUEDAD = 'LIMITE_ANTIGUEDAD',
  LIMITE_CATEGORIA = 'LIMITE_CATEGORIA',
  POLITICA_CENTRO_COSTO = 'POLITICA_CENTRO_COSTO',
  CONFIG_CATEGORIA = 'CONFIG_CATEGORIA',
}
